---
- name: restart sshd
  systemd:
    name: sshd
    state: restarted

- name: restore iptables
  shell: |
    iptables-restore < /etc/iptables/rules.v4
    ip6tables-restore < /etc/iptables/rules.v6
