keys:
  - &users
    - &zepzeper age17k6cvpgyjcda35epql3804wyq77zmtmpvwrjyetvcttr50j8e5xqj98cfv
    - &ds10u-server age1nsxvxpnegvaxvunr8h6zm3vqkt8fnhnxnnjv0x2z2vca88c8td7sh3fhrr
  - &hosts
    - &desktop age17k6cvpgyjcda35epql3804wyq77zmtmpvwrjyetvcttr50j8e5xqj98cfv
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
        - *zepzeper
        - *desktop
        - *ds10u-server
