keys:
  - &users:
    - &zepzeper age1h7nrzudldl77vx4tsd6tvm3k062yjyjtjd4mdvpwp8qxdkgu0y7qtsvk9a
  - &hosts:
    - &nixix: age1ruadjdqmttwcyvn6hpfwhn5867d73rvztehn4v78y3cqnz2ezf3qqlk7cd
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
        - *zepzeper
        - *nixix
