grafana:
  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      external-dns.alpha.kubernetes.io/target: 192.168.68.241
    hosts:
      - grafana.home
    path: /
    pathType: Prefix
