---
server_hostname: "pi"
platform: "aarch64"

# SSH public keys for admin user
admin_ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILw5Pf5z3KZ8Q6m0q9v2x1R4H7JkY3Wt8BnLpX9cVf2a zepzeper@desktop"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD5WB8PM5rtjJ6EFI/qC1BYEUtHZjmYQIGh7kpPjsfHRb2yWoBBT5ZFPIr/8VQNkRwZFhKVXZo+nmyF9CycwqxHtEgSSuCTHrBXRmJXd6dcRKYUxhc7CsWOGyGDuvAsROa4HEUMxw5TjVEQi6DFd3YOmjG+DA5LlCp6+oa4ZQH8kYSZf59pqSvTM1OZXLCQce+/iFI+6Mag0m60277dypAGjGhXL4jnu0Csh1sGSSmxsYlrP2JYVzQBrKfPZL0q7Xx2VsP+MfIyN7/DGe/E9juwESjEhW3VVAUVav35Di6UUM3zLdMObZZvfTwq4awofHMgr2dzCwRv+kDbtLSxV4Aj"

# Boot configuration
boot_loader: "generic-extlinux-compatible"
boot_efi: false
disk_device: "/dev/mmcblk1"
