---
- name: Full deploy - bootstrap then k3s then manifests
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - common
    - server

- name: Deploy Tailscale and K3s
  hosts: k3s:all
  become: yes
  gather_facts: yes
  roles:
    - tailscale
    - k3s

- name: Deploy K3s manifests
  hosts: k3s_master
  become: yes
  gather_facts: yes
  roles:
    - k3s-manifests
