---
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  ingressClassName: nginx-internal
  hosts:
    - "pihole.home"
serviceWeb:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
  LoadBalancerIP: 192.168.68.240
serviceDns:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
  LoadBalancerIP: 192.168.68.240
replicaCount: 1
