# ./values/wireguard.values.yaml

replicaCount: 1

service:
  #type: LoadBalancer
  #loadBalancerIP: 192.168.68.241
  type: NodePort
  port: 51820

wireguard:
  # Set your own custom network
  serverAddress: 10.13.13.1/24
  serverCidr: 10.13.13.0/24

  port: 51820
  
  # Use your Pi-hole DNS
  interfaceOpts:
    DNS: 192.168.68.240

  peers:
    - name: iPhone-wouter
      publicKey: "wvEgoRz/0ZWoRSSPHf2Znc1MURBcTHGBe0W2v/QVOgg="
      allowedIPs:
        - 10.13.13.2/32

securityContext:
  privileged: true
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

persistence:
  enabled: true
  size: 1Gi
  storageClass: "longhorn"

# Enable Prometheus metrics (optional)
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
  dashboard:
    enabled: false

# Set to false since we're running a single node
autoscaling:
  enabled: false

daemonSet: false

# We only have one node, so disable disruption budget
disruptionBudget:
  enabled: false
